### ISSUE TITLE
Conversion Exception 

### ISSUE THREAD

**Issue by greeny277** [Galigator/openllet#27] opened 2017-11-01 19:40 UTC
I'm using Openllet for queries on my ontology as suggested [here](https://github.com/Galigator/openllet/blob/integration/examples/src/main/java/openllet/examples/SPARQLDLExample.java). Afterwards I try to convert the given individuals to [org.apache.jena.ontology.Individual](https://jena.apache.org/documentation/javadoc/jena/org/apache/jena/ontology/Individual.html) which causes the Exception. Im not sure if it is a Jena Bug or caused by Openllet. I already opened [ticket](https://issues.apache.org/jira/browse/JENA-1415) on the JENA Dashboard.
If it is not related to Openllet, I'm sorry for bothering.

Here is the testcode:
```java
package bug;

import openllet.jena.PelletReasonerFactory;
import openllet.query.sparqldl.jena.SparqlDLExecutionFactory;
import org.apache.jena.ontology.OntModel;
import org.apache.jena.query.Query;
import org.apache.jena.query.QueryExecution;
import org.apache.jena.query.QueryFactory;
import org.apache.jena.query.QuerySolution;
import org.apache.jena.query.ResultSet;
import org.apache.jena.query.ResultSetFormatter;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.ontology.Individual;
import org.apache.jena.ontology.OntClass;
import org.apache.jena.util.iterator.ExtendedIterator;

import java.util.ArrayList;

public class SPARQLDLBug
{

	// The ontology loaded as dataset
	private static final String ontology = "ontologies/simple.owl";

	private static final String query = "query.sparql";
	public void run()
	{
			// First create a Jena ontology model backed by the Pellet reasoner
			// (note, the Pellet reasoner is required)
			final OntModel m = ModelFactory.createOntologyModel(PelletReasonerFactory.THE_SPEC);

			// Then read the _data from the file into the ontology model
			m.read(ontology);

			// Now read the query file into a query object
			final Query q = QueryFactory.read(query);

			// Create a SPARQL-DL query execution for the given query and
			// ontology model
			final QueryExecution qe = SparqlDLExecutionFactory.create(q, m);

			// We want to execute a SELECT query, do it, and return the result set
			final ResultSet rs = qe.execSelect();

			ArrayList<String> result = new ArrayList<String>();

			while(rs.hasNext()){
				QuerySolution qs = rs.next();
                                // The Bug occurs in the next line
				Individual in = qs.getResource("x").as(Individual.class);
				ExtendedIterator<OntClass> it = in.listOntClasses(true);

				String className = "";
				while(it.hasNext()){
					className = it.next().toString();
				}
				result.add(className);	
			}

			qe.close();
	}

	public static void main(final String[] args)
	{
		final SPARQLDLBug app = new SPARQLDLBug();
		app.run();
	}
}
```
Here is the simple query:
```xml
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
 PREFIX owl: <http://www.w3.org/2002/07/owl#>
 PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
 PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
 PREFIX bio: <http://www8.cs.fau.de/research:cgm/schizophrenia#>
 SELECT ?x
 WHERE { ?x rdf:type bio:AcuteSchizophrenia }

```
And this is the error message:
```bash
Exception in thread "main" org.apache.jena.ontology.ConversionException: Cannot convert node http://www8.cs.fau.de/research:cgm/schizophrenia#R_AcuteSchizophrenia to Individual
        at org.apache.jena.ontology.impl.IndividualImpl$1.wrap(IndividualImpl.java:61)
        at org.apache.jena.enhanced.EnhNode.convertTo(EnhNode.java:152)
        at org.apache.jena.enhanced.EnhNode.convertTo(EnhNode.java:31)
        at org.apache.jena.enhanced.Polymorphic.asInternal(Polymorphic.java:62)
        at org.apache.jena.enhanced.EnhNode.as(EnhNode.java:107)
        at bug.SPARQLDLBug.run(SPARQLDLBug.java:58)
```
The ontology consists of a class and one individual only:
```xml
<?xml version="1.0"?>
<rdf:RDF xmlns="http://www8.cs.fau.de/research:cgm/schizophrenia#"
     xml:base="http://www8.cs.fau.de/research:cgm/schizophrenia"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:swrlb="http://www.w3.org/2003/11/swrlb#"
     xmlns:swrl="http://www.w3.org/2003/11/swrl#"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     xmlns:dc="http://purl.org/dc/elements/1.1/">
    <owl:Ontology rdf:about="http://www8.cs.fau.de/research:cgm/schizophrenia">
    </owl:Ontology>

    <!-- http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral -->

    <rdfs:Datatype rdf:about="http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral"/>

    <owl:Class rdf:about="http://www8.cs.fau.de/research:cgm/schizophrenia#AcuteSchizophrenia">
        <rdfs:label xml:lang="en">Acute schizophrenia</rdfs:label>
    </owl:Class>


        <owl:NamedIndividual rdf:about="http://www8.cs.fau.de/research:cgm/schizophrenia#R_AcuteSchizophrenia">
        <rdf:type rdf:resource="http://www8.cs.fau.de/research:cgm/schizophrenia#AcuteSchizophrenia"/>
    </owl:NamedIndividual>

</rdf:RDF>
```

Best regards,
Christian

**Comment by Galigator** [comment] 2017-11-01 21:13
Thx for your example.

The problem is in `.as(Individual.class)` , because sparql answer of sparql don't have OWL type, you can directly cast an Resource (an answer) into an Individual.
Looking at the query there is no way to tell if 'x' is an Individual, Property, or Class.
Imagine a different ontology, you could have more than one result, first could be an Individual and second an Property.

So to get the classes of the Resource 'x' you may need another query in the form :
`?onClass owl:Class 'x'`

**Comment by greeny277** [comment] 2017-11-01 22:38
Thanks a lot.
I've written another query as you told: 
```xml
 SELECT ?onClass
 WHERE { ?onClass owl:Class ?x}
```
It is invoked with the first QuerySolution. Sadly it returns an empty set and the following warning:
```
openllet.jena.graph.query.GraphQueryHandler findTriple No query handler found for * http://www.w3.org/2002/07/owl#Class http://www8.cs.fau.de/research:cgm/schizophrenia#R_AcuteSchizophrenia
```
Any idea what I'm still missing?

**Comment by LorenzBuehmann** [comment] 2017-11-02 07:52
I don't know what you guys are trying to achieve, but neither

`?onClass owl:Class 'x'`

nor

`?onClass owl:Class ?x`

are useful triple patterns in SPARQL and won't match any RDF data. `owl:Class` is never used as predicate and I guess you mean something different.

Please understand that an individual is assigned to a class by `rdf:type` relation.

If I assume that you want to find the classes of a given individual, the query should look like

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?cls WHERE {
 <THE_URI_OF_THE_INDIVIDUAL> rdf:type ?cls
}
```

**Comment by greeny277** [comment] 2017-11-02 11:43
Thanks a lot @LorenzBuehmann . This does it for me.

**Comment by greeny277** [comment] 2017-11-02 11:58
Dave Reynolds suggests on the [Dashboard](https://issues.apache.org/jira/browse/JENA-1415?focusedCommentId=16235417&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16235417) that 
> [...] SparqlDLExecutionFactory is returning resources that aren't in the expected model [...]

His workaround does it for me either:
`Individual in = qs.getResource("x").inModel(m).as(Individual.class);`

**Comment by Galigator** [comment] 2017-11-02 13:07
After doing some tracing in the code, I found where the model change.
I belive, the model change because the result is build from the KB not from the original model.
The result could can contains resources that aren't part of the original model but are created by reasoning : like "Inv(property)".

I am not sure of the expected behaviour.
By the way none of the examples using Sparql(neither in pellet-2.3.6-ansell) are working, so I have to repairs them before tagging this as a bug or a feature.

**Comment by Galigator** [comment] 2017-11-02 15:23
I just commit a correction for the sparql example.


Dave Reynolds say the issue is in Openllet... he's opinion.

All the classes involve in the construction of the Resource are from Jena.
The logical chain is the following :

```java
Dataset dataset = DatasetFactory.create(modelFromUser);
 //Here reasoning on the dataset take place.
Model model = dataset.getDefaultModel();
new org.apache.jena.sparql.core.ResultBinding(model, binding); // this is the result.

```

This look clear to me, I see no reason to change it; issue is in Jena way to interact with world.

**Closed** 2017-11-07 18:43 UTC
Labels: help wanted, question
